### ISSUE TITLE
INCLUDE lines being duplicated, causing errors

### ISSUE THREAD

**Issue by SpriggsySpriggs** [FellippeHeitor/InForm#100]
This is, I suppose, actually a QB64 error but it seems to only happen when I use InForm. If I don't fix an error on a line fast enough, it will duplicate the '$INCLUDE:'InForm\InForm.ui' line, causing more errors,

**Comment by FellippeHeitor** [comment]
That should have been fixed in 1.3. Are you in 1.3?

**Comment by FellippeHeitor** [comment]
This was the fix to QB64 https://github.com/Galleondragon/qb64/commit/a4a2b4f6dbf5ca5b93ac1f11d3894c21d6dc7405

**Comment by SpriggsySpriggs** [comment]
Yes, I am using 1.3
If it matters, I'm using the 32 Bit version of QB64.

**Comment by FellippeHeitor** [comment]
Interesting. I'll try to reproduce it. Thanks for reporting.

**Comment by FellippeHeitor** [comment]
Fixed in upcoming v1.4 of QB64: 498d2cee54b0b635c484749ab4a98494d5139550 yay! 🎉
