### ISSUE TITLE
Clicking on an empty Enabled ListBox quits the program

### ISSUE THREAD

**Issue by CallumMcEwen** [FellippeHeitor/InForm#104]
I compiled the StopWatch example program and noticed that if I click on the empty ListBox at the bottom of the window it quits the program. I have also noticed this happening in my own software creation using two ListBoxes. If the ListBox is empty or disabled the program does not quit.

QB64 x64 1.3, Win10 Pro 1909 Update.

Callum

P.S Keep up the great work. InForm is really useful.

**Comment by FellippeHeitor** [comment]
Thanks for reporting. What version/build of InForm is it? If 1.1, do you have development updates enabled in the Options menu?

![](https://user-images.githubusercontent.com/10699359/68828690-5aae2280-0685-11ea-8f4b-140b68425c45.png)

That way it'll be easier to deliver a fix to you sooner.

**Comment by CallumMcEwen** [comment]
Hi Fellippe

I'm using V1.1 build 11. I have selected development versions now.

Thanks

**Comment by Plutonium5793** [comment]
Are there any instructions for installing this under Fedora linux (rpm). ?  qb64 does, but there appears to be no provision for this program.
Thanks for any help,
John

**Comment by FellippeHeitor** [comment]
@Plutonium5793 Hi, not yet. For now you'd have to grab the installer from www.qb64.org/inform (or compile manually by downloading the repository)

**Comment by FellippeHeitor** [comment]
Fixed and uploaded to update server. Please let me know if InForm will offer to download build 13.

**Comment by CallumMcEwen** [comment]
Updated to build 13. Issue resolved. Thank you for the quick fix.

Happy New Year

Regards
Callum
