### ISSUE TITLE
String from binary file displayed correctly several times before permanently breaking

### ISSUE THREAD

**Issue by SpriggsySpriggs** [FellippeHeitor/InForm#107]
I made a little program for playing mp3 audio files. It displays album art as well as the metadata from the file displayed in the labels I made. It worked several times back to back but suddenly, after I compiled it once more, it stopped displaying the strings in the labels correctly. Below is the output as it shows when I make a standard QB64 program:
![good return of information](https://user-images.githubusercontent.com/10662502/74236088-6e761e80-4c9e-11ea-86ab-e28b29e67359.png)
The code for that output is:
![code for console version](https://user-images.githubusercontent.com/10662502/74236099-76ce5980-4c9e-11ea-9bc2-abccb9f59da6.png)
When I translate that code into a sub to use in InForm it looks like this:
![bad encoding or wrong page code](https://user-images.githubusercontent.com/10662502/74236129-8b125680-4c9e-11ea-8419-12848445dcfe.png)
![code for inform version](https://user-images.githubusercontent.com/10662502/74236131-8e0d4700-4c9e-11ea-8974-514236eb5a10.png)
I don't know what happened or why it suddenly does not work anymore. I've reinstalled QB64 v1.3 and re-installed InForm. I installed QB64 v1.4 and still no luck. Do you have any idea why it would suddenly stop or how I could go about fixing it?

**Comment by SpriggsySpriggs** [comment]
I would have shown a screenshot of how it looked when it worked but I didn't think about needing it at the time because I didn't anticipate a permanent breakage.

**Comment by SpriggsySpriggs** [comment]
I think I might have found a workaround by using a shell command to call the program it does work in and reading the output from it back into the InForm version.

**Comment by FellippeHeitor** [comment]
That's most curious. I could have a closer look if you're willing to share your files (mp3 included).

**Comment by FellippeHeitor** [comment]
Also: which build of InForm?

**Comment by FellippeHeitor** [comment]
aaaaaaaaaaaaah, I have a suspicion. try this:

```FreeFileHandle% = FREEFILE
OPEN SongFile$ FOR BINARY AS #FreeFileHandle%```

Then replace all instances of hard-coded "1" (in `LOF(1)` and in `GET #1`) to FreeFileHandle% (`LOF(FreeFileHandle%)` and `GET #FreeFileHandle%`)

**Comment by SpriggsySpriggs** [comment]
That didn't work either. It behaved the same way with either showing nothing in the labels at all or showing garbled text. That's ok though. I can still just use the other program by calling it and getting the data. No worries!

**Comment by FellippeHeitor** [comment]
Big worries. If you decide to share the files, I’ll be around.

**Comment by SpriggsySpriggs** [comment]
Here are the files. Attached also is the program I'm using to call using SHELL to get the correct data.
I hope this gives you some clue as to why it happens.
Also, I tried to see if I opened the mp3 file in my program and instead of immediately reading into the labels, I output the information into a text file and read it back. Still received the same garbled result. It only gives me a clear result when using a regular QB64 program.

[songTags.bas.txt](https://github.com/FellippeHeitor/InForm/files/4204545/songTags.bas.txt)

[Music Player GUI.bas.txt](https://github.com/FellippeHeitor/InForm/files/4204508/Music.Player.GUI.bas.txt)
[Music Player GUI.frm.txt](https://github.com/FellippeHeitor/InForm/files/4204511/Music.Player.GUI.frm.txt)

[07 BANG BANG BANG.zip](https://github.com/FellippeHeitor/InForm/files/4204525/07.BANG.BANG.BANG.zip)

**Comment by SpriggsySpriggs** [comment]
I guess you might also want these so you won't have all those "Missing File" warnings in the program.

![Big_Note](https://user-images.githubusercontent.com/10662502/74534074-fb201700-4f00-11ea-99b2-55c6115cb229.png)
![loop](https://user-images.githubusercontent.com/10662502/74534077-fbb8ad80-4f00-11ea-8901-177136b09915.png)
![open-folder](https://user-images.githubusercontent.com/10662502/74534078-fc514400-4f00-11ea-9541-90fbf5e872a0.png)
![fast-forward](https://user-images.githubusercontent.com/10662502/74534080-fc514400-4f00-11ea-8697-f7d6a8eb29a1.png)
![rewind](https://user-images.githubusercontent.com/10662502/74534082-fc514400-4f00-11ea-9139-ba20e453c01a.png)

![pause](https://user-images.githubusercontent.com/10662502/74534121-125f0480-4f01-11ea-962c-0871eb421a02.png)
![play-flat](https://user-images.githubusercontent.com/10662502/74534123-125f0480-4f01-11ea-936d-6c58d4dd8300.png)
![Stop1NormalRed](https://user-images.githubusercontent.com/10662502/74534124-125f0480-4f01-11ea-9cc6-465ea4294345.png)

**Comment by SpriggsySpriggs** [comment]
Also, apologies for not seeing your reply asking for my build of InForm. I'm using build 11.

**Comment by SpriggsySpriggs** [comment]
[songinfo.txt](https://github.com/FellippeHeitor/InForm/files/4205729/songinfo.txt)
[songinfo.txt](https://github.com/FellippeHeitor/InForm/files/4205739/songinfo.txt)
Here are two examples. New mp3 file. The one with valid data came from the function written using a standard QB64 program. The second one with garbled text came from the InForm version.

**Comment by SpriggsySpriggs** [comment]
I see where someone else from last year had a similar issue:
https://github.com/FellippeHeitor/InForm/issues/97

**Comment by FellippeHeitor** [comment]
Hi, I found the bug in your program. To fix it, you must **add `DIM position AS LONG` in `SUB GetSongTags`**.

The issue here is that your variable `position`, which you were using to calculate where to start reading the tags in the MP3 file, was being defined as an INTEGER, which overflows at 32767. That didn't happen in the standalone version because there was no `DEFINT A-Z` there (you used this in the InForm version for the code to get the Open Dialog) and the default data type in QB64 is SINGLE, which can go above the INTEGER limit.

Then, when position was an INTEGER and you attempted to set it to a value higher than 32767 (in this case, LOF(file) minus some arbitrary number), you'd end up overflowing and going negative, which created all sort of garbage by actually reading wave data from the MP3 file.

**Comment by SpriggsySpriggs** [comment]
I appreciate the help. While what you told me fixed the issue it still doesn't explain why it would work for several times in the InForm version before stopping suddenly when I made no code changes in-between it working and it not working.

Thank you for looking into this, though.

**Comment by FellippeHeitor** [comment]
You sure adding the Open Dialog code isn't what made the difference?
