### ISSUE TITLE
Unable to run on macOS 10.12.6

### ISSUE THREAD

**Issue by tamsinadriane** [FellippeHeitor/InForm#111]
I'm trying to install this along with qb64 on macOS 10.12.6, and as a non-programmer, it's proving typically tricky. I've installed the xcode libraries, and run the InFormSetupMac executable three times. Each time, the terminal displays the following:

```
Last login: Tue Mar 17 11:24:19 on ttys000
Tamsin-Michaels-MacBook:~ tamsin.michael$ /Users/tamsin.michael/Downloads/qb64/InFormSetupMac ; exit;
QB64 Compiler V1.4
exewithsource = false
QB64 Compiler V1.4

Beginning C++ output from QB64 code... first pass finished.
Translating code... 
[..................................................] 100%
Warning: 25 unused variables

Compiling C++ code into executable...
Output: UiEditor
QB64 Compiler V1.4

Beginning C++ output from QB64 code... first pass finished.
Translating code... 
[..................................................] 100%
Warning: 23 unused variables

Compiling C++ code into executable...
Output: /Users/tamsin.michael/Downloads/qb64/InForm/UiEditorPreview
QB64 Compiler V1.4

Beginning C++ output from QB64 code... first pass finished.
Translating code... 
[..................................................] 100%
Warning: 7 unused variables

Compiling C++ code into executable...
Output: /Users/tamsin.michael/Downloads/qb64/InForm/updater/InFormUpdater
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

```
Then I'm prompted to run InForm, select "Yes", and nothing happens. Could this have something to do with the unused variables mentioned in the terminal? Is there a different set of xcode tools I should install? Even assuming that InForm has been installed properly, how should I run it (the UIEditorPreview executable in the InForm directory just tells me to run the main program, which I can't seem to find)? 

Let me know if you need any further info. Thanks in advance!

**Comment by FellippeHeitor** [comment]
All seems proper. Compilation ok (`Output: UiEditor`, `Output: /Users/tamsin.michael/Downloads/qb64/InForm/UiEditorPreview`, `Output: /Users/tamsin.michael/Downloads/qb64/InForm/updater/InFormUpdater`), meaning that the Xcode tools you got are all good to go.

In a terminal window, go to your qb64 folder and try running `./UiEditor`

It should pop a warning asking for permission to connect locally over TCP/IP and that's that.

The Warnings can be safely ignored.

Let me know if that works, please.
---
I'm on macOS 10.15.3 and it works - but I did test it before on older versions, as I developed it.

It could be something in your firewall settings blocking it.

**Comment by tamsinadriane** [comment]
Hmm. I tried to change directories and run ./UIEditor from the terminal, but the terminal seemed to just pause for a moment and then display another command prompt, as if the program had crashed (?). Trying to run it directly from the Finder yields the following:

```
Tamsin-Michaels-MacBook:~ tamsin.michael$ /Users/tamsin.michael/Downloads/qb64/UiEditor ; exit;
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```
My firewall is turned off, so I'm not sure what else could be interfering with it.

Thanks!

**Comment by FellippeHeitor** [comment]
You don't seem to be at QB64's folder when you run `./UiEditor'

Please try to `cd` there first and then run `./UiEditor` and let me know how that goes.

**Comment by FellippeHeitor** [comment]
(Hope you've had a change to try it as I stated above, @tamsinadriane - please let me know).

**Comment by tamsinadriane** [comment]
Thank you so much - I just came back to it and was able to run it directly from the macOS GUI! Now to figure out how to use it...

**Comment by FellippeHeitor** [comment]
Let me know if there's anything I can assist you with. Thank you so much for your interest!
