### ISSUE TITLE
unable to run in ubuntu 20.04 (under QB64)

### ISSUE THREAD

**Issue by zy74** [FellippeHeitor/InForm#112]
hi,i'm not expert 
i'm try to run InForm under qb64 in ubuntu 20.04 64bit HDD installed(Kernel 5.4.0-29-generic).
after install by InFormSetup_Debian64  (downld,complile are OK)but when i launch :./UiEditor..
i retrive:InForm designer is not running.Pleaserun the main program!
thanks in advance && sorry my english
![inform1](https://user-images.githubusercontent.com/65091706/81484732-5a639e00-9248-11ea-86cd-60dde94d9c9a.png)
![inform2](https://user-images.githubusercontent.com/65091706/81484735-5f285200-9248-11ea-8201-35cf3529cd06.png)

**Comment by FellippeHeitor** [comment]
Hello. I've been meaning to change the handshake timeout for linux for a while now, as this is a known issue. Latest patch, applied today (00f28644629c4b4a8cf8332f0c990b7a6feeeadd) should get you going. https://github.com/FellippeHeitor/InForm/archive/development.zip

**Comment by zy74** [comment]
worked like a sharm! thanks so much

**Comment by Fifi-fr** [comment]
If I may, there is a small trick to avoid this problem without asking to Fellippe to modify the handsahe timeout each time there is a new release whatever the Linux distribution and desktop environment you use:
- Once you've downloaded and unpacked InFom as requested (to the QB64 main folder), first load and compile the UiEditorPreview.bas file (located in the InForm sub folder) WITH the option "Output EXE to Source Folder" on, to place the UiEditorPreview executable to the InForm folder,
- Then load and compile the UiEditor.bas file (also located in the InForm sub folder) but now WITHOUT the option "Output  EXE to Source Folder", to place the UiEditor executable to the QB64 main folder.
Now there is also the other solution to use my multi-lingual installation bash script for Linux that installs (and can cleanly uninstall) QB64, InForm and vWATCH64 alltogether that you can get here: [http://www.as2.com](url)
