### ISSUE TITLE
[Feature Suggestion] A Texteditor Control

### ISSUE THREAD

**Issue by Shakey-Games** [FellippeHeitor/InForm#113]
The only way a user running a form can input text is with the Textbox control.
Textboxes are meant for a small amount of input, one line only.

A Texteditor control would function the same as a textbox, but it would be meant for large amounts of text input. The text would be aligned from the top-left, and would have both a vertical and a horizontal scrollbar. The Text editor doesn't have to have it's text set by the user: the developer can write text in it as well. The control can also be disabled (greyed-out and unable to have text written). See below for an example.
 
![image](https://user-images.githubusercontent.com/68006824/86907147-84342680-c10c-11ea-8009-e532254555ff.png)

This control is useful for creating Text Editor software, retrieving large amounts of text input from the user, or displaying large amount of text to the user.

**Comment by FellippeHeitor** [comment]
Hi, and thanks for the suggestion. It is already an open issue, though - check #19 - so I'll have this one closed.

**Comment by Shakey-Games** [comment]
> Hi, and thanks for the suggestion. It is already an open issue, though - check #19 - so I'll have this one closed.

Ah, understood.
