### ISSUE TITLE
InForm.ui error message

### ISSUE THREAD

**Issue by paulo810** [FellippeHeitor/InForm#115]
First, I love still being able to use and create Basic programs in Windows 10 and especially like the InForm addition.
I have a basic app I created last year using InForm, simple app, works 100% of the time.

A few days ago I installed file version 2.0.2.0 of the QB64 Compiler and InForm Designer v1.3 (build 20).

I loaded the app I created in a previous version of InForm into the newest version, saved it and went to QB64. After the code loads I see the following Status message and the app willl not execute:

Illegal SUB/FUNCTION parameter in line 4385 of C:\:qb64\InForm\InForm.ui included on line 31.

My line 31 = '$INCLUDE:'InForm\InForm.ui'

Any idea what the issue might be as the version of my app works perfectly in the prior version 1.4 of QB64 and version 1.2 (build 15) of InForm?

Thanks Paul

**Comment by FellippeHeitor** [comment]
Beginning with v1.3 of InForm, `InForm/InForm.ui` has been split into 2 files: `InForm/InForm.bi`, which must come at the top together with your .frm file include line, and `inForm/InForm.ui`, which must come at the end of your .bas file. To see how it should be, create a new blank project with InForm and save it, so you can inspect the results. Sorry for the inconvenience.

**Comment by paulo810** [comment]
Wow! I never expected to get such a quick response from you. Thank you so
much. I will do as you suggest and report back to you as soon as possible.

**Comment by paulo810** [comment]
Just did a quick test app as you suggested, worked perfectly.

Added the InForm.bi to my old app and moved InForm.ui include line to the end, ran the app and it also worked perfectly. 

Thanks again for the quick response and fortunately for me, simple solution!

**Comment by FellippeHeitor** [comment]
My pleasure, Paulo. Let me know if any other issues come up.

BTW, Paulo... are you Brazilian by any chance?

**Comment by paulo810** [comment]
American, my first name is Paul, Last name begins with O. lol

**Comment by FellippeHeitor** [comment]
Lol!

**Comment by paulo810** [comment]
Boa noite meu amigo!
