### ISSUE TITLE
Library not found in line 13 '$INCLUDE:'InForm\InForm.bi' [FIXED]

### ISSUE THREAD

**Issue by SkyQuest99** [FellippeHeitor/InForm#119]
OS = Windows 10 Pro
QB64 VERSION = v2.1 from https://qb64.com/
INFROM VERSION = v1.3

When I make the bas and the frm file, the bas file keeps on giving me ('$INCLUDE:'InForm\InForm.bi'  Library not found)
And when I enter that file it shows me this code DECLARE LIBRARY "falcon"
Any Ideas on how to fix this

**Comment by SkyQuest99** [comment]
Ok I

**Comment by SkyQuest99** [comment]
Only works for windows I think.. but It worked in QB64(www.qb64.com) v2.1 and v.1.4
TO fix this problem copy the falcon.h file from the Inform file
![image](https://user-images.githubusercontent.com/71566490/218257278-a195cc0c-0589-4170-9f4a-6b3396432986.png)
Paste it on your qb64 program folder
![image](https://user-images.githubusercontent.com/71566490/218257377-89b9f36a-bda2-4771-a80d-c23fb3409ed4.png)
Now its fixed

**Comment by SkyQuest99** [comment]
> Only works for windows I think.. but It worked in QB64([www.qb64.com](http://www.qb64.com)) v2.1 and v.1.4 TO fix this problem copy the falcon.h file from the Inform file ![image](https://user-images.githubusercontent.com/71566490/218257278-a195cc0c-0589-4170-9f4a-6b3396432986.png) Paste it on your qb64 program folder ![image](https://user-images.githubusercontent.com/71566490/218257377-89b9f36a-bda2-4771-a80d-c23fb3409ed4.png) Now its fixed

**Comment by FellippeHeitor** [comment]
Glad you got around it.
