### ISSUE TITLE
Replace disk approach with TCP/IP for data exchange.

### ISSUE THREAD

**Issue by FellippeHeitor** [FellippeHeitor/InForm#48]

**Comment by callowaysutton** [comment]
Wait wait wait, What is this?...

**Comment by FellippeHeitor** [comment]
InForm's editor and the Preview form are two separate application running and exchanging data via a disk file. The Preview is constantly sending the form data back to the editor and the editor sends edits over to the Preview by writing to disk. I intend to replace that paradigm with a local TCP/IP connection between both. Under tests locally already ;-)

**Comment by callowaysutton** [comment]
Woahhhh that's really smart, what do you think the benefits would be?

**Comment by FellippeHeitor** [comment]
Just switching to a more modern approach is already a benefit, but I envision you could load more than a form at once, for one thing (which would make sense considering the planned enhancement described in #20).

I also imagine that the burden on the disk is going to be magnitudes smaller this way, of course - especially considering the many reads/writes per minute that the editor currently has to perform. The first versions of InForm had issues with flushing to disk on Linux machines, which I had to circumvent by opening and close the exchange files multiple times a second.

Now I will consider this switch a success if the end-user ends up not noticing that I've changed it at all. The idea is to make it as seamless as possible.

**Comment by FellippeHeitor** [comment]
Effective for Beta 8 starting with 420c0f6e792c23ba6522b812d17aff7b08788526
