### ISSUE TITLE
Request: Control bindings 

### ISSUE THREAD

**Issue by FellippeHeitor** [FellippeHeitor/InForm#55]
Control properties could be assigned to another control's properties so that, for example, clicking a toggle control would change another control's .Disabled property. Something like:

Bind Control(Toggle1).Value, Control(List1).Disabled

**Comment by FellippeHeitor** [comment]
Maybe in another programming language.

**Comment by callowaysutton** [comment]
Wait what do you mean maybe in another programming language?

**Comment by FellippeHeitor** [comment]
It won't be possible to implement the idea in QB64, that's what I meant, unfortunately.

**Comment by callowaysutton** [comment]
Are you thinking of using a C library?

**Comment by FellippeHeitor** [comment]
Not for now.
