### ISSUE TITLE
Program, if left untouched for a while, will freeze when attempting usage

### ISSUE THREAD

**Issue by zspriggs19** [FellippeHeitor/InForm#96]
I have created a program that uses a SQL query to populate a dropdown list with records from the database. It allows the user to print a label from the database to a label printer by running another query using the item they selected and writing the results to a printable text file. However, if I start the program and do not use it for approximately 10 minutes and decide to use it later, the program freezes immediately when I choose to click any button or other interactive object. I'm not sure where the issue is rooted. Is this just an issue with InForm or is it more likely an issue with my code? My code also fires PowerShell scripts for an open file dialog, a print dialog, and two data entry scripts. If I use it constantly without taking long breaks, the program works fine. It only freezes if I choose to wait about 10-15 minutes between interactions.

**Comment by FellippeHeitor** [comment]
You could try creating a simple program with a few controls without all the bulk of your full-blown program and let it rest on your desktop, to check whether it's on InForm's end or not. Please let me know your OS and QB64 version as well. I haven't had it happen to me. One of my programs is a simple database but it doesn't use SQL, so it doesn't crash on me (not saying it's that, but something could be interacting weirdly there). Please let me know.

**Comment by zspriggs19** [comment]
Thank you for your response. I'll check it out on my end here and see what is causing it.
