### ISSUE TITLE
can't use unicode string in caption

### ISSUE THREAD

**Issue by retsyo** [FellippeHeitor/InForm#97]
as the title says

btw, where can we find more eye-catching demo of InForm

**Comment by retsyo** [comment]
no, I found that the unicode character can't display correclty in InForm, but can display in the QB64-built exe

**Comment by FellippeHeitor** [comment]
Hi. That’s a limitation of QB64 itself, as it doesn’t handle Unicode on its own, so InForm inherits that.

There are a few demos at www.qb64.org/inform/demos
