### ISSUE TITLE
Inform Beta 8 Won't Start

### ISSUE THREAD

**Issue by zspriggs19** [FellippeHeitor/InForm#98]
I used Inform just yesterday but now it simply will not start. It shows up in the processes list but never displays. I have reinstalled and I have restarted my computer. Still will not display.

**Comment by FellippeHeitor** [comment]
Windows? Recently updated OS?

**Comment by zspriggs19** [comment]
> Windows? Recently updated OS?

Yes, I have recently updated to build 1903 of Windows 10. However, the Inform Designer worked perfectly up until today. I managed to get it working for a bit after using the clean.bat tool in the qb64 folder and reinstalling 3 times but it has stopped working again.

**Comment by zspriggs19** [comment]
It must have been a computer issue rather than an Inform issue. I've been able to reopen Inform several times now over different lengths of time successfully.
