### ISSUE TITLE
Maximizing and Auto Centering

### ISSUE THREAD

**Issue by SpriggsySpriggs** [FellippeHeitor/InForm#99]
Is there an option or will there be an option in the future for having fullscreen applications that have auto centering/auto sizing controls? I suppose that can be achieved by just using the QB64 _FULLSCREEN command and just editing the size and position at runtime in the meantime.

**Comment by callowaysutton** [comment]
You can already do this using the _RESIZE function in QB64, just multiply whatever percent you want.
Add this into 
```
IF _RESIZE THEN rx& = _RESIZEWIDTH: ry& = _RESIZEHEIGHT
```

Having this built in would be a nice feature but its not really necessary

**Comment by FellippeHeitor** [comment]
You sure can take an InForm application fullscreen, but that's not really the goal, since we're creating forms to take user input. It wouldn't make much sense to occupy the whole screen just for that.

**Comment by SpriggsySpriggs** [comment]
It would be handy for someone in tablet mode on Windows 10.

**Comment by callowaysutton** [comment]
> It would be handy for someone in tablet mode on Windows 10.

True, I was also thinking about using Inform last year when a school wanted me to make some check-in software for them (they ended up contracting someone elsewhere)
